<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Plugin.Uno.MVVMExpress.Pagination.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Plugin.Uno.MVVMExpress.Pagination\Plugin.Uno.MVVMExpress.Pagination.csproj" />
    <ProjectReference Include="..\..\src\Plugin.Uno.MVVMExpress.Testing\Plugin.Uno.MVVMExpress.Testing.csproj" />
  </ItemGroup>

</Project>
