<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Plugin.Uno.MVVMExpress.Dialogs.Tests</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Plugin.Uno.MVVMExpress.Dialogs\Plugin.Uno.MVVMExpress.Dialogs.csproj" />
    <ProjectReference Include="..\..\src\Plugin.Uno.MVVMExpress\Plugin.Uno.MVVMExpress.csproj" />
    <ProjectReference Include="..\..\src\Plugin.Uno.MVVMExpress.Testing\Plugin.Uno.MVVMExpress.Testing.csproj" />
  </ItemGroup>

</Project>
