<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UnoMvvmExpressVersion>1.0.0</UnoMvvmExpressVersion>
  </PropertyGroup>
</Project>
